### ISSUE TITLE
Can you include steps for x86  boot 

### ISSUE THREAD

**Issue by Istech-Tech** [dvtirol/pynetinstall#1]
Can you include steps for x86  boot  it also seem dhtest wont extra image

**Comment by uedvt359** [comment]
Have you tried `PXEClient`  for dhtest -o?

**Comment by Istech-Tech** [comment]
yes does not seem help or missing something i think image just call /image but am not sure

**Comment by uedvt359** [comment]
Please write down all the steps you did, including the output. I can't help you with the information you've given so far

**Comment by Istech-Tech** [comment]
basicly run net install cli on ethernet interface  with -i  and the router os npk winch if boot machine pxe on that interface x86 it boot  try to ru dhtest -i  interface name -v  not tcpdump show images

/images i have try to user curl tftp to get image  curl tftp:// ip address /image > netinstall_x86

**Comment by Istech-Tech** [comment]
mind you i did not notice it  said it always name linux.arm try that not but does not apear to be working

**Comment by Istech-Tech** [comment]
still missing somethign maybe some stupid i dont know i think i have format right

**Comment by Istech-Tech** [comment]
I dont if help but tcpdump show file as just /image

**Comment by uedvt359** [comment]
OK, maybe they use image as the bootfilename on x86. Can you post your tcpdump? That would help debugging this tremendously. As you said, you should then be able to download it with `curl -v tftp://127.0.0.1/image > netinstall.x86`. What does curl print (with `-v` to show the logs) when you try that?

**Comment by Istech-Tech** [comment]
![Screenshot from 2023-07-07 02-55-39](https://github.com/dvtirol/pynetinstall/assets/13160584/40899833-3dc2-4e99-b050-a73158fcb156)

screen shot

**Comment by Istech-Tech** [comment]
> OK, maybe they use image as the bootfilename on x86. Can you post your tcpdump? That would help debugging this tremendously. As you said, you should then be able to download it with `curl -v tftp://127.0.0.1/image > netinstall.x86`. What does curl print (with `-v` to show the logs) when you try that?

I cant seem to get curl grab it just says transport error not sure if image should be call image 

or boot_x86

**Comment by Istech-Tech** [comment]
if any one want know you can extract 
x86 mikotik install image
Install image 

boot file seem to bootx64.efi  winch seem let it boot netboot  image not sure what next step is

**Comment by uedvt359** [comment]
I found some time today to reproduce the issue. send the following dhcp request: `sudo dhtest -T 5 -o "PXEClient" -i lo -c 93,hex,0007`. Notably, it requires option 93, documented here: https://www.rfc-editor.org/rfc/rfc4578#section-2.1

it does not matter if you tftp-get `/image` or `linux.arm` - they both return the same file (I suspect that the tftp server doesn't even look at the filename)

**Comment by Istech-Tech** [comment]
tcpdump: listening on enp0s8, link-type EN10MB (Ethernet), snapshot length 262144 bytes
01:42:13.277552 IP (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 294)
    0.0.0.0.bootpc > 255.255.255.255.bootps: [udp sum ok] BOOTP/DHCP, Request from 08:00:27:be:6e:b6 (oui Unknown), length 266, xid 0x50ed425b, Flags [none] (0x0000)
        Client-Ethernet-Address 08:00:27:be:6e:b6 (oui Unknown)
        Vendor-rfc1048 Extensions
          Magic Cookie 0x63825363
          DHCP-Message (53), length 1: Discover
          Parameter-Request (55), length 5:
            Subnet-Mask (1), BR (28), Default-Gateway (3), Domain-Name (15)
            Domain-Name-Server (6)
          Vendor-Class (60), length 9: "PXEClient"
          ARCH (93), length 2: 7

01:44:18.188242 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::a00:27ff:febe:6eb6 > ip6-allrouters: [icmp6 sum ok] ICMP6, router solicitation, length 16
        source link-address option (1), length 8 (1): 08:00:27:be:6e:b6
          0x0000:  0800 27be 6eb6

**Comment by Istech-Tech** [comment]
is that tcpdump that but that with net install it does not even show tftp image transfer it just show   dhcp output
