### ISSUE TITLE
Automatic detection and uploading of firmware based on device arch

### ISSUE THREAD

**Issue by CoMMyz** [dvtirol/pynetinstall#2]
Hi,

This tool is amazing and works lovely. Is there any plugin ready that can upload the firmware/config found in a specific folder based on architecture ?

Thank you!

**Comment by uedvt359** [comment]
sorry for the late reply, something like this should do the trick. at least for `arm64` and `arm`(32), the `info.arch` contains exactly the strings that are part of the default file names from mikrotik (other architectures may need a dict lookup). of course you can also load this from a local directory, not just over http.

let me know if this work for you!

config.ini:
```ini
[pynetinstall]
plugin=dvt:DVTPlugin
ros_version=7.11
default_config=config.rsc
```

dvt.py:
```python
from urllib.parse import quote

class DVTPlugin:
    def __init__(self, config):
        self.ros_version = config["pynetinstall"]["ros_version"]
        self.default_config = config["pynetinstall"]["default_config"]

    def get_files(self, info):
        mac = info.mac.hex(':').upper()
        model = quote(info.model)
        arch = info.arch

        firmware = f"https://download.mikrotik.com/routeros/{self.ros_version}/routeros-{self.ros_version}-{arch}.npk"

        return firmware, self.default_config
```

**Comment by rfdrake** [comment]
Just in case others want to try this, here is a working example.

For config.ini, I specified the directory where I put the dvt.py file (the same directory that simple.py is in):
```
[pynetinstall]
plugin=pynetinstall.plugins.dvt:DVTPlugin
ros_version=7.15.1
default_config=config.rsc
```


For dvt.py, I made multiple modifications.  First, the architecture of the devices doesn't always match what is in the routeros filename, so I translate that with a table.  The second thing I wanted was to allow different config files based on architecture and model.   This checks to see if a default.rsc file exists in the arch or model folder, then falls back to a general config if nothing specific is found.
```
from urllib.parse import quote
from os.path import isfile

arch_name = {
    "mips": "mipsbe"
}

class DVTPlugin:
    def __init__(self, config):
        self.ros_version = config["pynetinstall"]["ros_version"]
        self.default_config = config["pynetinstall"]["default_config"]

    def get_files(self, info):
        mac = info.mac.hex(':').upper()
        model = quote(info.model)
        arch = arch_name[info.arch] if info.arch in arch_name else info.arch
        # would be nice if I could specify this in the config.ini.  I'll see
        # if I can figure out a way to make it configurable there.
        config = self.default_config
        if isfile(f"/configs/{arch}/{model}/default.rsc"):
            config = f"/configs/{arch}/{model}/default.rsc"
        elif isfile(f"/configs/{arch}/default.rsc"):
            config = f"/configs/{arch}/default.rsc"

        firmware = f"/routeros/{self.ros_version}/{arch}/routeros-{self.ros_version}-{arch}.npk"

        return firmware, config
```

**Comment by uedvt359** [comment]
>        # would be nice if I could specify this in the config.ini.  I'll see
>        # if I can figure out a way to make it configurable there.

assuming you mean the `arch_name` table: this in `__init__()` should work:

    self.arch_name = dict(element.split(":", maxsplit=1) for element in cf['pynetinstall']['arch_table'].splitlines())

with the following config:

```
[pynetinstall]
arch_table = mips:mipsbe
	test:foo
```

(any indentation on the following lines is ok)
