### ISSUE TITLE
error creating build container

### ISSUE THREAD

**Issue by vangelis86** [dvtirol/pynetinstall#7]
Hi im facing an issue by building an mmips architecture image while its ok when im using arm for example

export arch=mmips
buildah build --arch=${arch} --format docker --tag pynetinstall-${arch} .
STEP 1/5: FROM alpine:3
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/alpine:3...
error creating build container: choosing an image from manifest list docker://alpine:3: no image found in manifest list for architecture mmips, variant "", OS linux

**=========================================================================**

export arch=arm
buildah build --arch=${arch} --format docker --tag pynetinstall-${arch} .
STEP 1/5: FROM alpine:3
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/alpine:3...
Getting image source signatures
Copying blob da2748c71804 done
Copying config e1540075d4 done
Writing manifest to image destination
Storing signatures
STEP 2/5: RUN apk update && apk add python3
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/armv7/APKINDEX.tar.gz
v3.20.3-283-g7adfc4fa250 [https://dl-cdn.alpinelinux.org/alpine/v3.20/main]
v3.20.3-285-gc7e81630276 [https://dl-cdn.alpinelinux.org/alpine/v3.20/community]
OK: 22689 distinct packages available
(1/17) Installing libbz2 (1.0.8-r6)
(2/17) Installing libgcc (13.2.1_git20240309-r0)
(3/17) Installing libexpat (2.6.4-r0)
(4/17) Installing libffi (3.4.6-r0)
(5/17) Installing gdbm (1.23-r1)
(6/17) Installing xz-libs (5.6.2-r0)
(7/17) Installing libstdc++ (13.2.1_git20240309-r0)
(8/17) Installing mpdecimal (4.0.0-r0)
(9/17) Installing ncurses-terminfo-base (6.4_p20240420-r1)
(10/17) Installing libncursesw (6.4_p20240420-r1)
(11/17) Installing libpanelw (6.4_p20240420-r1)
(12/17) Installing readline (8.2.10-r0)
(13/17) Installing sqlite-libs (3.45.3-r1)
(14/17) Installing python3 (3.12.7-r0)
(15/17) Installing python3-pycache-pyc0 (3.12.7-r0)
(16/17) Installing pyc (3.12.7-r0)
(17/17) Installing python3-pyc (3.12.7-r0)
Executing busybox-1.36.1-r29.trigger
OK: 43 MiB in 31 packages
STEP 3/5: COPY pynetinstall /pynetinstall
STEP 4/5: VOLUME /config
STEP 5/5: ENTRYPOINT /usr/bin/python3 -m pynetinstall -c /config/pynetinstall.ini -v
COMMIT pynetinstall-arm
Getting image source signatures
Copying blob 821917525934 skipped: already exists
Copying blob 79a77100bf25 done
Copying config 213a503f1d done
Writing manifest to image destination
Storing signatures
--> 213a503f1d6
Successfully tagged localhost/pynetinstall-arm:latest
213a503f1d677fc7f764e83b700a7bc39b22630edb5da73519ef5d39d367d6d6

**Comment by uedvt359** [comment]
i can't provide general help for docker questions.

mikrotik only provides the container subsystem for arm and aarch64, so you won't be able to use your mips based routerboard to host pynetinstall anyhow.
